### ISSUE TITLE
Message decoding check required.

### ISSUE THREAD

**Issue by vivekr20** [davebshow/gremlinclient#14]
https://github.com/davebshow/gremlinclient/blob/445677732400eab0d1d8a1c6006981a26527b0e2/gremlinclient/connection.py#L319

If the underlying WebSocket response message is already decoded, this call breaks.
Ideally, there should be a check to accommodate this.
Maybe assume already decoded if this line throws?

**Comment by vivekr20** [comment]
This might do the trick:

try:
    message = json.loads(result.decode("utf-8"))
except AttributeError as e:
    message = json.loads(result)

**Comment by davebshow** [comment]
Hi @vivekr20. I'm curious about this issue. Does the Gremlin Server ever return a message that isn't bytes? Have you seen an error here? If so, could you post code to reproduce it?

Also, as a side note, this project is basically inactive. Instead, I would recommend that you use either `aiogremlin`, `Goblin`, or the official `gremlinpython`.

**Comment by vivekr20** [comment]
Hi David,

Thank you for your response. I think It really depends on how the server chooses to send data over WebSocket?
I’ve been working on Cosmos DB’s Gremlin Server, and if I configure the server to send data as String over WebSocket, I get the below error:


“AttributeError("'str' object has no attribute'decode'”

Full Call Stack:
“
ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x0000025B97449AE8>, <tornado.concurrent.F
uture object at 0x0000025B97438E48>)
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\tornado\ioloop.py", line 600, in _run_callback
    ret = callback()
  File "C:\Program Files\Python36\lib\site-packages\tornado\stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\gremlinclient\connection.py", line 319, in parser
    message = json.loads(result.decode("utf-8"))
AttributeError: 'str' object has no attribute 'decode'
”

Thanks for the pointers to the other clients BTW. I’m trying to build better compatibility for Cosmos DB’s gremlin API with Python client drivers, so the pointers will help! ☺
To start with, I want to build a few “hello world” samples for connecting to cosmos DB’s gremlin API using the one’s mentioned below.
Could I reach out to you later, if I have any issues with working these client drivers?

Thanks,
Vivek

**Comment by davebshow** [comment]
I would be happy to help you with anything related to the Python TinkerPop libraries. I would also love to see examples with CosmosDB. Please ping me with a link if you get anything up.

**Comment by vivekr20** [comment]
That would be greatly appreciated :) Will do!
